# Generated by Django 5.1.4 on 2025-03-04 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.CharField(blank=True, help_text='Department responsible for the project', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='field',
            field=models.CharField(blank=True, help_text='Field or area of the project', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='academic_year',
            field=models.CharField(blank=True, help_text='Academic year', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Project description', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Name of the project', max_length=200),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.IntegerField(choices=[(1, 'Reader'), (2, 'Committee Member'), (3, 'Supervisor')], help_text='User role in the project'),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Project duration (in weeks or months)', null=True),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='goals',
            field=models.TextField(blank=True, help_text='Project goals', null=True),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='outputs',
            field=models.TextField(blank=True, help_text='Expected outputs', null=True),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='tasks',
            field=models.TextField(blank=True, help_text='Project tasks', null=True),
        ),
        migrations.CreateModel(
            name='ProjectProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the proposed project', max_length=200)),
                ('team_member_count', models.IntegerField(help_text='Number of team members required')),
                ('field', models.CharField(help_text='Field or area of the project', max_length=200)),
                ('department', models.CharField(help_text='Department responsible for the project', max_length=200)),
                ('description', models.TextField(help_text='Description of the project')),
                ('additional_comment', models.TextField(blank=True, help_text='Any additional comments', null=True)),
                ('attached_file', models.FileField(blank=True, help_text='Optional file attachment', null=True, upload_to='project_proposals/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the proposal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(help_text='User who submitted this proposal', on_delete=django.db.models.deletion.CASCADE, related_name='project_proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='proposal',
            field=models.OneToOneField(blank=True, help_text='The proposal that generated this project (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_project', to='project.projectproposal'),
        ),
    ]
