# Generated by Django 5.1.7 on 2025-03-11 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_projectmembership_unique_together_and_more'),
        ('users', '0002_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coordinator',
            field=models.ForeignKey(blank=True, help_text='Coordinator responsible for the project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='users.coordinator'),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor managing the project (teacher who accepted the proposal)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='users.supervisor'),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='group_id',
            field=models.CharField(blank=True, help_text="Identifier for the student's group in the project", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='proposed_to',
            field=models.ForeignKey(blank=True, help_text='If submitted by a student, specify the recipient (e.g. teacher/coordinator)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='team_members',
            field=models.ManyToManyField(blank=True, help_text='For student proposals: list the team members who will work on the project', related_name='team_proposals', to='users.student'),
        ),
        migrations.CreateModel(
            name='AnnualGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(help_text='Annual grade given by the supervisor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_grades', to='project.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_annual_grades', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_annual_grades', to='users.supervisor')),
            ],
            options={
                'unique_together': {('supervisor', 'student', 'project')},
            },
        ),
    ]
