# Generated by Django 5.1.7 on 2025-04-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='coord_id',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
    ]
