# Generated by Django 5.1.7 on 2025-03-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_department_usercreationlog'),
    ]

    operations = [
    ]
