# Generated by Django 4.2.19 on 2025-03-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='is_super',
            field=models.BooleanField(default=False),
        ),
    ]
