# Generated by Django 5.1.7 on 2025-04-20 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationform',
            name='coordinators',
            field=models.ManyToManyField(blank=True, related_name='evaluation_forms', to='users.coordinator'),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='target_role',
            field=models.ForeignKey(blank=True, help_text='The role of users for whom this evaluation form is intended.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='evaluation_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_categories', to='form.evaluationform'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='form.maincategory'),
        ),
    ]
