# Generated by Django 4.2.19 on 2025-05-07 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationform',
            name='coordinators',
            field=models.ManyToManyField(blank=True, related_name='evaluation_forms', to='users.coordinator'),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='target_role',
            field=models.ForeignKey(blank=True, help_text='The role of users for whom this evaluation form is intended.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role'),
        ),
    ]
