# Generated by Django 5.1.7 on 2025-04-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationform',
            name='form_weight',
            field=models.FloatField(default=0.5, help_text='The weight of the entire evaluation form.'),
            preserve_default=False,
        ),
    ]
