# Generated by Django 5.1.7 on 2025-05-02 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectfeedback',
            old_name='receiver',
            new_name='teacher',
        ),
        migrations.RemoveField(
            model_name='projectfeedback',
            name='is_reply',
        ),
        migrations.AddField(
            model_name='projectfeedback',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='FeedbackReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='feedbacks.projectfeedback')),
            ],
        ),
        migrations.AddField(
            model_name='feedbackfile',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='feedbacks.feedbackreply'),
        ),
    ]
