# Generated by Django 5.1.7 on 2025-03-11 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0001_initial'),
        ('project', '0004_alter_projectmembership_unique_together_and_more'),
        ('users', '0002_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_id', models.CharField(max_length=20, unique=True)),
                ('grade', models.FloatField()),
                ('final_grade', models.FloatField()),
                ('evaluation_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='form.evaluationform')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grading_id', models.CharField(max_length=20, unique=True)),
                ('final_grade', models.FloatField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradings', to='grades.grade')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_grade_id', models.CharField(max_length=20, unique=True)),
                ('final_grade', models.FloatField()),
                ('evaluation_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_grades', to='form.evaluationform')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_grades', to='grades.grade')),
                ('grading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_grades', to='grades.grading')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_grades', to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='MemberGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='grades.grade')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graded_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberIndividualGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluators', to='grades.individualgrade')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_graded_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
