# Generated by Django 5.1.7 on 2025-05-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text="Optional deadline. After this time, the announcement won't be shown.", null=True),
        ),
    ]
