# Generated by Django 5.1.7 on 2025-05-20 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_announcementfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='attachment',
        ),
    ]
