# Generated by Django 5.1.7 on 2025-04-20 23:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=django.utils.timezone.now, help_text='Date of the report')),
                ('progress', models.TextField(blank=True, help_text='Summary of overall progress', null=True)),
                ('work_done', models.TextField(blank=True, help_text='Work completed during this period', null=True)),
                ('work_remaining', models.TextField(blank=True, help_text='Work pending for the next period', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_progress', models.TextField(blank=True, help_text='Overall monthly progress summary', null=True)),
                ('month_plan', models.TextField(blank=True, help_text='The plan for the next month', null=True)),
            ],
            options={
                'verbose_name': 'Monthly Report',
                'verbose_name_plural': 'Monthly Reports',
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=django.utils.timezone.now, help_text='Date of the report')),
                ('progress', models.TextField(blank=True, help_text='Summary of overall progress', null=True)),
                ('work_done', models.TextField(blank=True, help_text='Work completed during this period', null=True)),
                ('work_remaining', models.TextField(blank=True, help_text='Work pending for the next period', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenges', models.TextField(blank=True, help_text='Challenges faced during the week', null=True)),
                ('goals_next_period', models.TextField(blank=True, help_text='Goals for the next week/bi-week', null=True)),
            ],
            options={
                'verbose_name': 'Weekly Report',
                'verbose_name_plural': 'Weekly Reports',
            },
        ),
    ]
