# Generated by Django 5.1.7 on 2025-04-20 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_initial'),
        ('report', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='created_by',
            field=models.ForeignKey(help_text='Supervisor who created this report', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='project',
            field=models.ForeignKey(help_text='The project this report is for', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reports', to='project.project'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='team_members',
            field=models.ManyToManyField(help_text='Team members working on the project included in this report', related_name='%(class)s_team_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='created_by',
            field=models.ForeignKey(help_text='Supervisor who created this report', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='project',
            field=models.ForeignKey(help_text='The project this report is for', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reports', to='project.project'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='team_members',
            field=models.ManyToManyField(help_text='Team members working on the project included in this report', related_name='%(class)s_team_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
