# Generated by Django 4.2.19 on 2025-05-11 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('project', '0004_feedbackexchange_task'),
        ('report', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('progress', models.TextField(blank=True, null=True)),
                ('work_done', models.TextField(blank=True, null=True)),
                ('work_remaining', models.TextField(blank=True, null=True)),
                ('challenges', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_reports', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMemberStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_statuses', to='report.projectreport')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
            options={
                'unique_together': {('report', 'student')},
            },
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='project',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='team_members',
        ),
        migrations.DeleteModel(
            name='MonthlyReport',
        ),
        migrations.DeleteModel(
            name='WeeklyReport',
        ),
    ]
