# Generated by Django 4.2.19 on 2025-05-07 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0002_initial'),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberindividualgrade',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_graded_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membergrade',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='grades.grade'),
        ),
        migrations.AddField(
            model_name='membergrade',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graded_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individualgrade',
            name='evaluation_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_grades', to='form.evaluationform'),
        ),
        migrations.AddField(
            model_name='individualgrade',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_grades', to='grades.grade'),
        ),
        migrations.AddField(
            model_name='individualgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_grades', to='users.student'),
        ),
        migrations.AddField(
            model_name='grading',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gradings', to='project.project'),
        ),
        migrations.AddField(
            model_name='grading',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradings', to='users.student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='evaluation_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='form.evaluationform'),
        ),
        migrations.AddField(
            model_name='grade',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='form.maincategory'),
        ),
        migrations.AddField(
            model_name='grade',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='project.project'),
        ),
        migrations.AlterUniqueTogether(
            name='memberindividualgrade',
            unique_together={('member', 'individual_grade')},
        ),
        migrations.AlterUniqueTogether(
            name='membergrade',
            unique_together={('member', 'grade')},
        ),
    ]
