# Generated by Django 5.1.7 on 2025-04-18 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0002_initial'),
        ('grades', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grading',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradings', to='users.student'),
        ),
        migrations.AddField(
            model_name='individualgrade',
            name='evaluation_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_grades', to='form.evaluationform'),
        ),
        migrations.AddField(
            model_name='individualgrade',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_grades', to='grades.grade'),
        ),
        migrations.AddField(
            model_name='individualgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_grades', to='users.student'),
        ),
        migrations.AddField(
            model_name='membergrade',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='grades.grade'),
        ),
        migrations.AddField(
            model_name='membergrade',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graded_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memberindividualgrade',
            name='individual_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluators', to='grades.individualgrade'),
        ),
        migrations.AddField(
            model_name='memberindividualgrade',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_graded_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='membergrade',
            unique_together={('member', 'grade')},
        ),
        migrations.AlterUniqueTogether(
            name='memberindividualgrade',
            unique_together={('member', 'individual_grade')},
        ),
    ]
