# Generated by Django 5.1.7 on 2025-04-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grading',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
