# Generated by Django 5.1.7 on 2025-04-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(help_text='Annual grade given by the supervisor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(blank=True, help_text='Text of the feedback.', null=True)),
                ('feedback_file', models.FileField(blank=True, help_text='Optional file attached with the feedback.', null=True, upload_to='feedback_files/')),
                ('comment', models.TextField(blank=True, help_text='Optional comment.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the project', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Project description', null=True)),
                ('academic_year', models.CharField(blank=True, help_text='Academic year', max_length=20, null=True)),
                ('field', models.CharField(blank=True, help_text='Field or area of the project', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(blank=True, help_text='Identifier for the group in the project', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outputs', models.TextField(blank=True, help_text='Expected outputs', null=True)),
                ('goals', models.TextField(blank=True, help_text='Project goals', null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Project duration (in weeks or months)', null=True)),
                ('tasks', models.TextField(blank=True, help_text='Project tasks', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the proposed project', max_length=200)),
                ('team_member_count', models.IntegerField(help_text='Number of team members required')),
                ('field', models.CharField(help_text='Field or area of the project', max_length=200)),
                ('description', models.TextField(help_text='Description of the project')),
                ('additional_comment', models.TextField(blank=True, help_text='Any additional comments', null=True)),
                ('attached_file', models.FileField(blank=True, help_text='Optional file attachment', null=True, upload_to='project_proposals/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the proposal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(blank=True, help_text="Identifier for the student's group in the project", max_length=50, null=True)),
            ],
        ),
    ]
