# Generated by Django 4.2.19 on 2025-05-07 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprojectmembership',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_membership', to='users.student'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='users.student'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.projectgoal'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.project'),
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.department'),
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='proposed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='team_proposals', to='users.student'),
        ),
        migrations.AddField(
            model_name='projectplan',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='project.project'),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='project.project'),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectlog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='project.project'),
        ),
        migrations.AddField(
            model_name='projectlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectgoal',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='project.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='users.coordinator'),
        ),
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.department'),
        ),
        migrations.AddField(
            model_name='project',
            name='proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_project', to='project.projectproposal'),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='users.supervisor'),
        ),
        migrations.AddField(
            model_name='feedbackexchange',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_exchanges', to='project.project'),
        ),
        migrations.AddField(
            model_name='feedbackexchange',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_exchanges', to='project.projectproposal'),
        ),
        migrations.AddField(
            model_name='feedbackexchange',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackexchange',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annualgrade',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_grades', to='project.project'),
        ),
        migrations.AddField(
            model_name='annualgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_annual_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annualgrade',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_annual_grades', to='users.supervisor'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmembership',
            unique_together={('user', 'project', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='annualgrade',
            unique_together={('supervisor', 'student', 'project')},
        ),
    ]
