# Generated by Django 5.1.7 on 2025-04-23 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department responsible for the project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.department'),
        ),
    ]
