# Generated by Django 4.2.19 on 2025-05-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='research_file',
            field=models.FileField(blank=True, null=True, upload_to='research_files/'),
        ),
        migrations.AddField(
            model_name='project',
            name='show_research_to_students',
            field=models.BooleanField(default=False),
        ),
    ]
