# Generated by Django 5.1.7 on 2025-04-23 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_department'),
        ('project', '0004_auto_20250423_2010'),
    ]

    operations = [
    ]
