# Generated by Django 4.2.19 on 2025-05-20 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_annualgrade_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembership',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.projectproposal'),
        ),
    ]
