# Generated by Django 5.1.7 on 2025-03-17 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_coordinator_project_supervisor_and_more'),
        ('users', '0006_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='group_id',
            field=models.CharField(blank=True, help_text='Identifier for the group in the project', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='StudentProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(blank=True, help_text="Identifier for the student's group in the project", max_length=50, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_memberships', to='project.project')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_membership', to='users.student')),
            ],
        ),
    ]
