# Generated by Django 5.1.7 on 2025-03-21 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_projectmembership_group_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_group', models.CharField(blank=True, help_text='Identifier for the receiver group (if feedback is sent to a group).', max_length=50, null=True)),
                ('feedback_text', models.TextField(blank=True, help_text='Text of the feedback.', null=True)),
                ('feedback_file', models.FileField(blank=True, help_text='Optional file attached with the feedback.', null=True, upload_to='feedback_files/')),
                ('comment', models.TextField(blank=True, help_text='Optional comment.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(help_text='The project associated with this feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_exchanges', to='project.project')),
                ('receiver_user', models.ForeignKey(blank=True, help_text='Receiver of the feedback (if individual).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='User who sent the feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
