# Generated by Django 4.2.19 on 2025-05-20 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_coordinator_coord_id_and_more'),
        ('project', '0006_projectmembership_proposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmembership',
            name='proposal',
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='teacher_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role'),
        ),
    ]
