# Generated by Django 4.2.19 on 2025-04-05 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20250311_1307'),
        ('project', '0008_remove_feedbackexchange_receiver_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproposal',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department responsible for the project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.department'),
        ),
    ]
