# Generated by Django 4.2.19 on 2025-04-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_feedbackexchange_proposal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectproposal',
            name='status',
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='coordinator_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Status set by the assigned coordinator', max_length=20),
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='teacher_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Status set by the assigned teacher', max_length=20),
        ),
    ]
