# Generated by Django 4.2.19 on 2025-04-20 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_coordinator_is_super'),
        ('project', '0012_alter_project_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprojectmembership',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_membership', to='users.student'),
        ),
    ]
