# Generated by Django 4.2.19 on 2025-04-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_studentprojectmembership_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team_member_count',
            field=models.IntegerField(help_text='Number of team members required', null=True),
        ),
    ]
