# Generated by Django 4.2.19 on 2025-04-22 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20250311_1307'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_coordinator_is_super'),
        ('project', '0015_remove_projectplan_duration_remove_projectplan_goals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualgrade',
            name='grade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='feedbackexchange',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackexchange',
            name='feedback_file',
            field=models.FileField(blank=True, null=True, upload_to='feedback_files/'),
        ),
        migrations.AlterField(
            model_name='feedbackexchange',
            name='feedback_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackexchange',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_exchanges', to='project.project'),
        ),
        migrations.AlterField(
            model_name='feedbackexchange',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_exchanges', to='project.projectproposal'),
        ),
        migrations.AlterField(
            model_name='feedbackexchange',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedbackexchange',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='users.coordinator'),
        ),
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.department'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='field',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_project', to='project.projectproposal'),
        ),
        migrations.AlterField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='users.supervisor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_member_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='log_attachments/'),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='log_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='project.project'),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='group_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='completion_status',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='additional_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='project_proposals/'),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='coordinator_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.department'),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='field',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='proposed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='teacher_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='team_member_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='team_proposals', to='users.student'),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='users.student'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='deadline_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='deliverable_file',
            field=models.FileField(blank=True, null=True, upload_to='task_deliverables/'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='deliverable_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='goals',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='outputs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.project'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='task_status',
            field=models.CharField(choices=[('to do', 'To Do'), ('in progress', 'In Progress'), ('done', 'Done')], default='to do', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprojectmembership',
            name='group_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
