# Generated by Django 4.2.19 on 2025-04-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_alter_annualgrade_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproposal',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
