# Generated by Django 4.2.19 on 2025-04-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_projectproposal_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectplan',
            name='completion_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
