# Generated by Django 4.2.19 on 2025-04-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_alter_projectplan_completion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='remaining_tasks',
            field=models.TextField(blank=True),
        ),
    ]
