# Generated by Django 4.2.19 on 2025-04-26 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_projecttask_remaining_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='project.project'),
        ),
    ]
