# Generated by Django 4.2.19 on 2025-04-26 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_studentprojectmembership_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprojectmembership',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_proposal_memberships', to='project.projectproposal'),
        ),
    ]
