# Generated by Django 4.2.19 on 2025-04-27 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_alter_studentprojectmembership_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprojectmembership',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_memberships', to='project.project'),
        ),
    ]
