# Generated by Django 5.1.7 on 2025-04-20 23:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Scheduled date and time for the meeting.')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', help_text='Current status of the meeting.', max_length=20)),
                ('recommendation', models.TextField(blank=True, help_text='Recommendation or notes added by the supervisor after the meeting.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingFile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='File exchanged during the meeting.', upload_to='meeting_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_status', models.CharField(choices=[('pending', 'Pending'), ('attended', 'Attended'), ('absent', 'Absent')], default='pending', help_text='Attendance status for this participant.', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='File associated with the project.', upload_to='project_files/')),
                ('description', models.TextField(blank=True, help_text='Optional description of the file.', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
