# Generated by Django 5.1.7 on 2025-05-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingfile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='feedback_by_teacher',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='feedback_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
