# Generated by Django 5.1.7 on 2025-05-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_meetingfile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_report',
            field=models.TextField(blank=True, help_text='Filled by student after meeting is completed', null=True),
        ),
        migrations.DeleteModel(
            name='ProjectFile',
        ),
    ]
