# Generated by Django 5.1.7 on 2025-04-27 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_availabletime'),
        ('project', '0005_merge_20250423_2020'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project related to the meeting (if applicable).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='project.project'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='teacher',
            field=models.ForeignKey(default=1, help_text='Teacher the meeting is requested with.', on_delete=django.db.models.deletion.CASCADE, related_name='meetings_as_teacher', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingparticipant',
            name='has_accepted',
            field=models.BooleanField(default=False, help_text='Whether the participant has accepted the meeting request.'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the meeting.', max_length=20),
        ),
    ]
