# Generated by Django 5.1.7 on 2025-04-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_meeting_project_meeting_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='comment',
            field=models.TextField(blank=True, help_text='Message added when scheduling the meeting.', null=True),
        ),
    ]
