# Generated by Django 4.2.19 on 2025-05-07 10:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('meeting_request', 'Meeting Request'), ('meeting_accept', 'Meeting Accepted'), ('meeting_declined', 'Meeting Declined'), ('meeting_recomendation', 'Meeting Recomendation'), ('grade_released', 'Grade Released'), ('project_comment', 'Project Comment'), ('announcement', 'Announcement')], max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
