# Generated by Django 5.1.7 on 2025-04-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('meeting_request', 'Meeting Request'), ('meeting_accept', 'Meeting Accepted'), ('meeting_declined', 'Meeting Declined'), ('grade_released', 'Grade Released'), ('project_comment', 'Project Comment'), ('announcement', 'Announcement')], max_length=50),
        ),
    ]
