# Generated by Django 5.1.7 on 2025-05-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('meeting_request', 'Meeting Request'), ('meeting_accept', 'Meeting Accepted'), ('meeting_declined', 'Meeting Declined'), ('meeting_recomendation', 'Meeting Recomendation'), ('grade_released', 'Grade Released'), ('project_comment', 'Project Comment'), ('announcement', 'Announcement')], max_length=50),
        ),
    ]
