# Generated by Django 5.1.7 on 2025-03-11 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationForm',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_category_number', models.IntegerField()),
                ('main_category', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('type_of_grade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('sub_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_category', models.CharField(max_length=255)),
                ('evaluation_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='form.evaluationform')),
            ],
        ),
        migrations.CreateModel(
            name='EditEvaluationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_forms', to='users.coordinator')),
                ('evaluation_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_records', to='form.evaluationform')),
            ],
            options={
                'unique_together': {('coordinator', 'evaluation_form')},
            },
        ),
    ]
