# Generated by Django 5.1.7 on 2025-03-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationform',
            name='type_of_grade',
            field=models.CharField(choices=[('individual', 'Individual Grade'), ('group', 'Group Grade')], max_length=50),
        ),
    ]
