# Generated by Django 5.1.7 on 2025-03-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_evaluationform_type_of_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationform',
            name='form_name',
            field=models.CharField(default='Default Form', help_text='Name of the evaluation form', max_length=100),
        ),
    ]
